### PR TITLE
DR_0005_single-page-map-app

### PR DESCRIPTION
**Pull request by linzjax**
This PR provides a draft outlining the steps we're taking towards a single page map application.

All of this was previously outlined in a GitHub issue. Not sure if anything else needs to be added here.

Please add comments below.

### CODE REVIEW

**Review by wonderchook — APPROVED** [review]
Seems reasonable to me. I'm wondering if in implementation we can make make the overview and map tab a single page first and then do the additional pages in a subsequent sprint.

**Review by bjohare — APPROVED** [review]
Looks good to me.. one tiny thing.. should we rename the 'Map' tab to 'Locations' to be consistent with 'Parties' and 'Resources'?

**Comment by wonderchook** [comment]
@bjohare I've been wondering if we need both the overview tab and the map tab. I wonder how much use people get of the two. Maybe then it would remain as "map", though if we were to keep the overview tab then I think changing it to location makes sense. @clash99 what do you think? Is it worth worrying about right now?

**Comment by clash99** [comment]
With the map interaction project both location and party indexes will be available through the map tab.  The user will be able to see a map or list view of either location or party.  If we decide not to develop the list/map views, I would suggest adding a Location tab to be an index of locations similar to the Parties tab.

The overview was supposed to be sort of a "cover page/ dashboard" for the project.  I can see the map going away on that page completely and adding a lot more stats there.  Do you think this would be possible in the near future?  Or I can see us giving an overview closable panel on top of the map in the map tab and removing the overview tab completely.  If we aren't adding stats on the overview, then its really just the description and contact information.  That could also become a lower ranking "about" tab or even a link in a menu.  I think its good to have some sort of a project overview/cover page, especially for non-project users.

I think this is something we should consider getting user feedback on before making any changes.  What do you think @dpalomino and @wonderchook?

**Comment by wonderchook** [comment]
@clash99 agreed on getting the user feedback. I could see moving to an "about" or an "information" tab button for the time being. I'd be curious to hear from users how useful stats about their projects would be to them compared to other possible features.

**Comment by dpalomino** [comment]
Thanks @clash99 and all. Yes, I think it would be good to add more information regarding the project in the Overview/Dashboard project page and not providing the map in that page. 

Some ideas about the information we could provide: 
- Additional stats (as mentioned): we currently have locations, entities, resources. We could also add: 
    - last updated timestamp
    - number of records added in the last month (or even an usage graph showing the number of committed records in a timeline)
    - number of public users/project users/data collectors/project managers
    - total covered area (when supporting "Area of locations" feature)
- Links to custom reports (when available)
- Information regarding additional basemaps (when available)
- Links to survey forms (when supporting multiple survey forms)

**Comment by bjohare** [comment]
The Overview/Dashboard could potentially have a small 'overview' map in addition to more stats etc, rather than the large map we're currently using? If we do this, then perhaps we could disable the popups/links to locations from the smaller map so its really just an overview of the project extent and number of locations?

**Comment by oliverroick** [comment]
I agree, that the stats and links mentioned before are very nice to have, but they will _not_ be part of the ongoing work to implement the single page app. It's a separate task.

**Review by seav — APPROVED** [review]
The general idea is OK. Some details will still need to be hashed out but I have no broad objections or concerns with the proposed single-page map application architecture.

**Comment by linzjax** [comment]
Unless there are any additional comments, I think this is good to go.

**Pull request merged**
