### PR TITLE
DR_0010: External file handling

### PR DESCRIPTION
**Pull request by clash99**
This is to document our decision regarding handling of external files from June, 2017.

### CODE REVIEW

**Review by oliverroick — COMMENTED** [review]
- We should clarify that we're referring to JS libraries here. I got confused and thought this was about pulling in resources from external sources. 
- We also need to discuss and add a statement how this is going to be implemented:
  - Where do we host the files?
  - What's the update policy for those self-hosted files?
  - Do we maintain different versions to support different environments? Or will he have a repository for each of the environments?

**Comment by clash99** [comment]
@oliverroick - Thanks for the feedback. I've added a few bullet points to address your comments. Please review when you get a chance and let me know if you feel there should be more. I've kept it pretty lean.

**Review by oliverroick — COMMENTED** [review]
I think this looks ok. I'm not sure if we need to consider putting libraries on a CDN at this point? @amplifi what's your take?

**Comment by amplifi** [comment]
We wouldn't get any value from a CDN at this point. LGTM 👍

**Review by amplifi — APPROVED** [review]

**Comment by amplifi** [comment]
Follow-up: not sure whether it belongs in this DR, but we should also consider our internal file hosting. We currently have static files served from both local disk (`static/`) and S3 buckets. If we're going to continue to use both, there should be a cohesive policy around what assets live where.

**Review by oliverroick — APPROVED** [review]

**Comment by seav** [comment]
Do we need to mention here regarding the handling of JS files using Grunt for deployment (as implemented in the SMAP branch)?

**Comment by amplifi** [comment]
@seav No, that would be out of scope for this DR, and is already established in practice (not a decision).

Per conversation with @clash99 we're moving the few static assets hosted in S3 to `static/` for consistency. This PR is good to go.

**Pull request merged**
