### PR TITLE
DR_0001_blocking-questionnaire-upload

### PR DESCRIPTION
**Pull request by oliverroick**
First draft for DR 0001: Blocking update of questionnaires.

(It also serves as an example how to structure a decision record)

### CODE REVIEW

**Comment by ian-ross** [comment]
Looks good to me.

**Comment by dpalomino** [comment]
Thanks a lot @oliverroick for creating this. 

I agree with this, it is too dangerous to allow partners to update the XLSForm. I'm just thinking whether it'd be possible to allow the XLSForm update only for a superuser. This will allow us a workaround to make small changes in a more controlled environment. What do you think?

**Comment by oliverroick** [comment]
I'm not sure about this. It is very easy to upload a perfectly valid XLSForm and still break the jsonattrs structure, simply because there are no design restrictions in a spreadsheet. I would prefer to generally restrict it.

**Comment by amplifi** [comment]
Approved in dev team meeting 24 Nov 2016.

Phase 1: block ability to update
Phase 2: extend subset of abilities to super users
Phase 3: implement UI for schema changes

**Pull request merged**
