### PR TITLE
DR_0002_map-performance-upgrades

### PR DESCRIPTION
**Pull request by oliverroick**
This PR provides a draft towards a decision regarding how we want to improve the performance of the map. 

It currently shows three options how, in my opinion, the problem can be addressed. All three options are described very briefly, all need further research, discussions and in-depth description of the envisaged solution. I want us to agree on one approach before sketch out the details. 

Please add comments or other possible approaches below.

### CODE REVIEW

**Comment by bjohare** [comment]
Another possible approach might be to use a combination of Leaflet, [Topojson](https://github.com/topojson/topojson/wiki) and [D3](https://d3js.org/). We would need to convert `geojson` to `topojson` on the server, either on the fly or offline periodically. We could then provide an endpoint to retrieve the topojson asynchronously (possibly, spatially filtered by map extent). Here's an example using D3 to render 24K points using Leaflet and D3 http://bl.ocks.org/sumbera/10463358. This would obviously need to researched more thoroughly, for example the topojson may need to get converted back to geojson client-side which might defeat the purpose.. Also, D3 only supports modern browsers IE9 and above, but might be worth more investigation?

**Comment by seav** [comment]
@bjohare, do we actually need TopoJSON? This might make sense if partners want to ensure that adjacent parcels have coinciding boundaries (not overlapping nor having gaps). But we don't provide these kind of topological constraints in the platform when users create or edit location geometries.

**Comment by oliverroick** [comment]
I have updated the draft to reflect what we are going to do in the short-term. I we decide to do additional work that decision will go into another decision record.

**Comment by amplifi** [comment]
Approved in dev team meeting 24 Nov 2016

**Pull request merged**
